export const rizzlines = [
    "Are you a magician, [NAME]? Because whenever I look at you, everyone else disappears.",
    "Do you have a map, [NAME]? I keep getting lost in your eyes.",
    "Is your name Google, [NAME]? Because you've got everything I've been searching for.",
    "Are you a Wi-Fi signal, [NAME]? Because I'm feeling a connection.",
    "Excuse me, [NAME], but I think the stars tonight are outshone by your smile.",
    "If you were a vegetable, [NAME], you'd be a cute-cumber!",
    "Can I follow you home, [NAME]? Cause my parents always told me to follow my dreams.",
    "Are you a camera, [NAME]? Every time I see you, I smile.",
    "Is your name Ariel, [NAME]? Because we mermaid for each other.",
    "Do you have a Band-Aid, [NAME]? Because I just scraped my knee falling for you.",
    "Are you made of copper, [NAME], and tellurium? Because you're Cu-Te.",
    "Excuse me, [NAME], but I think you dropped something: MY JAW!",
    "If you were a cat, [NAME], you'd purr-fect.",
    "Do you have a sunburn, [NAME], or are you always this hot?",
    "Can I take a picture of you, [NAME], so I can show Santa exactly what I want for Christmas?",
    "Are you a parking ticket, [NAME]? Because you've got FINE written all over you.",
    "Do you believe in love at first sight, [NAME], or should I walk by again?",
    "Are you a time traveler, [NAME]? Because I can't imagine my future without you.",
    "Can I borrow a map, [NAME]? I keep getting lost in your eyes.",
    "If beauty were time, [NAME], you'd be an eternity.",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Is your name Google? Because you've got everything I've been searching for.",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "Excuse me, but I think the stars tonight are outshone by your smile.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "Are you a camera? Every time I see you, I smile.",
    "Is your name Ariel? Because we mermaid for each other.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "Excuse me, but I think you dropped something: MY JAW!",
    "If you were a cat, you'd purr-fect.",
    "Do you have a sunburn, or are you always this hot?",
    "Can I take a picture of you, so I can show Santa exactly what I want for Christmas?",
    "Are you a parking ticket? Because you've got FINE written all over you.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a time traveler? Because I can't imagine my future without you.",
    "Can I borrow a map? I keep getting lost in your eyes.",
    "If beauty were time, you'd be an eternity, [NAME].",
    "Do you have a sunburn, or are you always this hot?",
    "Can I take a picture of you, so I can show Santa exactly what I want for Christmas?",
    "Are you a parking ticket? Because you've got FINE written all over you.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a time traveler? Because I can't imagine my future without you.",
    "Can I borrow a map? I keep getting lost in your eyes.",
    "If beauty were time, you'd be an eternity.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Do you have a sunburn, or are you always this hot?",
    "Excuse me, but I think you dropped something: MY JAW!",
    "Are you a parking ticket? Because you've got FINE written all over you.",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Is your name Google? Because you've got everything I've been searching for.",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "Are you a camera? Every time I see you, I smile.",
    "Is your name Ariel? Because we mermaid for each other.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for",
]

export const evilRizzlines = [
    "I want you to know something, but I’m kinda scared to say it so I’ll let the first three words of this sentence say it for me",
    "I’d shoot my shot right now but I’m saving it for your back",
    "You want me, you want me, you want me",
    "Does the sun go down tonight or is it my turn?",
    "Hey Alexa, what’s my schedule look like for Saturday night? ",
    "No pen or paper but u still draw my attention 😮‍💨",
    "This must be a museum cause you’re truly a work of art 😮‍💨",
    "How strange, I dream of you even though I’m wide awake",
    "This may be a little bold of me to say but you’re invited to my wedding as my bride",
    "You tryna be FWB? 😳",
    "If I had a flower for each time I thought of you, I would be able to walk in my garden forever",
    "They say people can only be at one place at a time, but you’re both in my heart and my mind ",
    "If I were dared to shout to the world how much I love you, I would simply whisper it in your ears ",
    "For Your beauty is like clouds as you rain upon the earth or fill the world with sorrow your beauty is still far unimaginable",
    "All these stars but you shine the brightest",
    "Even if I was face to face with surya, it still wouldn’t compare to the warmth I feel when looking into your eyes",
    "They say Bhagwan makes no mistakes and yet I truly didn’t believe it until I laid my eyes on you ",
    "Are you a subway, cause you turn my 6 inch into a footlong ",
    "Are you spaghetti cause I want you to meet my balls",
    "If I had a flower for every time I thought of you, I would only have one flower, cause you never left my mind",
    "You me know whos perfect read the first word of the sentence",
    "If a spider bit me to make me Spider-Man, can you bite me to make me your man",
    "If you were on the other side of the road, I would cross the road without holding my moms hand for you 😮‍💨",
    "Ngl my brains tellin me red flag, but my hearts tellin me green",
    "We may have matched a few weeks ago but I’m ready to waste your time now ",
    "Just when I think I'm done, you appear and make me rethink everything.",
    "I have passed by many eyes, but I only got lost in yours",
    "The queen dying at 96 and not 100 means I’m the one 4 u",
    "Let’s play Hiroshima, I’ll lay on my back and you’ll blow the shit outta me ☢️",
    "I was walking my bird but the rain was on fire so my whale got arrested, basically we should make out ",
    "Honestly my favourite workout is you, wbu?",
    "Lowkey your bone structure is giving my bone a structure",
    "Will you be my tinderella???",
    "Aight I wrote a poem for u. You look very nice, I’m very impressed, can I shit on your chest",
    "What do your underpants and ketamine have in common? I’d love to sniff them both",
    "Aight I wrote a poem for u. Hello fine lady, could I make you my wife, I don’t feel like I have any purpose in life",
    "What did the fish say when it swam into the wall? Dam",
    "What’d you call a careful wolf? A werewolf",
    "Are you from a farm? Cause you sure know how to raise a cock",
    "I asked a French man if he played video games, he said Wii",
    "What type of bagels can fly? A plane bagel",
    "Damn you look outta this world, cause you look like an alien",
    "Do you have the Corona virus, cause I can’t stop looking achoo 🤧 ",
    "Out of all of your curves, your smile is my favourite",
    "Are you lookin for a stud cause I already have STD, all I need is U",
    "If you looking for Netflix and chill, you’re in the wrong place cause I’m more of an Amazon prime and quality time typa guy",
    "What’s the difference between sunglasses and you? Sunglasses sit higher on my face",
    "What’s the difference between an erection and a Ferrari? I don’t have a Ferrari ",
    "Are you Harambe’s enclosure, cause I wanna drop a kid in you",
    "I can give u sum sensational backshots and then we can watch a lil show and repeat whenever life stresses us out.",
    "Your breasts look heavy, do you need me to hold them for you? 😳",
    "I’m no dentist but I can give u a filling",
    "Do you want 12 inches of dick tonight, cause we can have sex 4 times ",
    "Just like the slippers in the masjid, you stole my heart",
    "Are you a sea lion, cause I can see you lyin in my bed tonight",
    "Are you a Pokémon, cause I’d love to peek at chu naked",
    "I’d love to take you to the movies, but they always get mad when I bring my own snack",
    "Are you Alice, cause your body looks like a wonderland",
    "I’m a big fan of your parents work",
    "Are you gotham? Cause I’d like to spend every single night protecting you (I’m mentally ill and genuinely think I’m Batman)",
    "What’s blue and not very heavy? Light blue 🫠",
    "I lost my teddy bear, can I sleep with you??? 🥺",
    "Did stars fall out of the skies and shine into your eyes?",
    "Are you sunburnt or are you always this hot??",
    "I may not go down in history, but I will go down on you ",
    "Would you like a normal hello or a terrible pickup line?",
    "This is an automated message reminding you of your upcoming HBO Max and Climax appointment, if you are still available for your appointment please reply “YES DADDY” to this message. ",
    "I’d suck your dads dick just to get a taste of what you’re made off 😍",
    "I’d say bless you but it looks like you already have been",
    "I’m going to complain to Spotify about you not being in this weeks hottest singles",
    "Kiss me if I’m wrong, but dinosaurs still exist, right?",
    "Let’s commit the perfect crime. I’ll steal your heart, you steal mine.",
    "Are you a fruit cause we would make a great pear.",
    "I assumed happiness started with an “H” but I believe it actually starts with “U”",
    "Hi, you don’t know my name but you can just call me tonight or tomorrow",
    "You're like my pinky toe, I'm gonna bang you on every piece of furniture in my home.",
    "There are 206 bones in the human body. How would you like one more?",
    "I'm a zombie, can I eat you out?",
    "You look so good; I wanna kiss your lips and then move up toward your belly button.",
    "How do you like your eggs: poached, scrambled, or fertilized?",
    "Do you have pet insurance? Because your kitty's getting smashed tonight.",
    "Are you my homework? Cause I'm not doing you, but I definitely should be.",
    "Your clothes are making me uncomfortable; please take them off.",
    "If I was the judge, I'd sentence you to my bed.",
    "Can I be honest? [Then after she replies.. reply with \"You're just my type.\"]",
    "Would you like to try an Australian kiss? It is just like a French kiss, but down under.",
    "What is a nice person like you doing in a dirty mind like mine?",
    "Do you go to church often? Because you're gonna be on your knees tonight.",
    "Will you help me get on Santa's naughty list this year?",
    "Do you have a cell phone in your back pocket? Because your ass is calling me.",
    "Are you an exam? Because I have been studying you like crazy.",
    "Let only latex stand between our love 🤩",
    "Are you a long structure used to restrict the flow of water across rivers and underwater streams? Because daaaaaaaaam!",
    "I wish you were soap so I could feel you all over me.",
    "I'm not a weatherman, but you can expect a few more inches tonight.",
    "One of my friends told me girls hate oral, do you wanna help me prove her wrong?",
    "I wish I was your phone, so you'd be on me all day.",
    "So, I guess we're dating now?",
    "I'll show you my tan lines if you'll show me yours.",
    "That's a beautiful smile, but it'd look even better if it were all you were wearing.",
    "I know exactly where I'm taking you on our first date..",
    "Would you rather be able to control the weather in a 1 mile radius? Or any time you clap, 3 tacos appear?",
    "Want a job? It blows.",
    "I'm a bird watcher and I'm looking for a Big Breasted Bed Thrasher. Have you seen one?",
    "What has four legs and doesn't have the most beautiful girl on it? My bed. Want to fix that?",
    "I'm scared of getting girls pregnant, so do you want to come over and help me test all my condoms?",
    "Wanna share your side of the bed tonight?",
    "For a girl that looks like you to still be single must mean that you have some serious problems ",
    "I’ve never killed a mountain lion, but I’ve always wanted to choke a cougar. Wyd this weekend???",
    "Ima be honest with you, i dont know why you’re playing hard to get when you’re already hard to like ",
    "Thinking of you keeps me awake, dreaming of you keeps me asleep, but being with you keeps me alive",
    "I find your lack of nudity disturbing",
    "Are you down to boink",
    "Head?",
    "Do you have feet?",
    "Wanna sploink?",
    "Holy shit I’m bout to expunge",
    "Ay Soulja boy wanna fuck",
]