export const rizzlines = [
    "Are you a magician, [NAME]? Because whenever I look at you, everyone else disappears.",
    "Do you have a map, [NAME]? I keep getting lost in your eyes.",
    "Is your name Google, [NAME]? Because you've got everything I've been searching for.",
    "Are you a Wi-Fi signal, [NAME]? Because I'm feeling a connection.",
    "Excuse me, [NAME], but I think the stars tonight are outshone by your smile.",
    "If you were a vegetable, [NAME], you'd be a cute-cumber!",
    "Can I follow you home, [NAME]? Cause my parents always told me to follow my dreams.",
    "Are you a camera, [NAME]? Every time I see you, I smile.",
    "Is your name Ariel, [NAME]? Because we mermaid for each other.",
    "Do you have a Band-Aid, [NAME]? Because I just scraped my knee falling for you.",
    "Are you made of copper, [NAME], and tellurium? Because you're Cu-Te.",
    "Excuse me, [NAME], but I think you dropped something: MY JAW!",
    "If you were a cat, [NAME], you'd purr-fect.",
    "Do you have a sunburn, [NAME], or are you always this hot?",
    "Can I take a picture of you, [NAME], so I can show Santa exactly what I want for Christmas?",
    "Are you a parking ticket, [NAME]? Because you've got FINE written all over you.",
    "Do you believe in love at first sight, [NAME], or should I walk by again?",
    "Are you a time traveler, [NAME]? Because I can't imagine my future without you.",
    "Can I borrow a map, [NAME]? I keep getting lost in your eyes.",
    "If beauty were time, [NAME], you'd be an eternity.",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Is your name Google? Because you've got everything I've been searching for.",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "Excuse me, but I think the stars tonight are outshone by your smile.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "Are you a camera? Every time I see you, I smile.",
    "Is your name Ariel? Because we mermaid for each other.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "Excuse me, but I think you dropped something: MY JAW!",
    "If you were a cat, you'd purr-fect.",
    "Do you have a sunburn, or are you always this hot?",
    "Can I take a picture of you, so I can show Santa exactly what I want for Christmas?",
    "Are you a parking ticket? Because you've got FINE written all over you.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a time traveler? Because I can't imagine my future without you.",
    "Can I borrow a map? I keep getting lost in your eyes.",
    "If beauty were time, you'd be an eternity, [NAME].",
    "Do you have a sunburn, or are you always this hot?",
    "Can I take a picture of you, so I can show Santa exactly what I want for Christmas?",
    "Are you a parking ticket? Because you've got FINE written all over you.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a time traveler? Because I can't imagine my future without you.",
    "Can I borrow a map? I keep getting lost in your eyes.",
    "If beauty were time, you'd be an eternity.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Do you have a sunburn, or are you always this hot?",
    "Excuse me, but I think you dropped something: MY JAW!",
    "Are you a parking ticket? Because you've got FINE written all over you.",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Is your name Google? Because you've got everything I've been searching for.",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "Are you a camera? Every time I see you, I smile.",
    "Is your name Ariel? Because we mermaid for each other.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for",
]